sonar.projectKey=MyApp
sonar.projectName=MyApp
sonar.projectVersion=1.0

sonar.sources=.

sonar.exclusions=**/node_modules/**,**/android/build/**,**/ios/**

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.token=squ_c2216dbfd54627c3eb75990b74d7879b2f59149d